// Code generated by scripts/gen-analytics-taxonomy.ts — DO NOT EDIT.
// Source: services/bff/internal/analytics/taxonomy.yml
// Generated: 2026-06-12

/**
 * Generated PostHog event name constants from taxonomy.yml.
 * All SPA PostHog emitters MUST use these constants for event names.
 * Do not hand-edit — run `make gen-taxonomy` to regenerate.
 */
export const Events = {
  /** Category: nav | Surface: spa | Consent: analytics */
  PAGE_VIEWED: 'page_viewed',
  /** Category: nav | Surface: spa | Consent: analytics */
  APP_SESSION_STARTED: 'app_session_started',
  /** Category: auth | Surface: spa | Consent: necessary */
  APP_USER_IDENTIFIED: 'app_user_identified',
  /** Category: auth | Surface: spa | Consent: necessary */
  APP_USER_SIGNED_OUT: 'app_user_signed_out',
  /** Category: auth | Surface: spa | Consent: analytics */
  FUNNEL_SIGN_UP_STARTED: 'funnel_sign_up_started',
  /** Category: auth | Surface: spa | Consent: analytics */
  FUNNEL_SIGN_UP_COMPLETED: 'funnel_sign_up_completed',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FUNNEL_DAEMON_DOWNLOAD_STARTED: 'funnel_daemon_download_started',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FUNNEL_DAEMON_CONNECTED: 'funnel_daemon_connected',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  FUNNEL_DAEMON_PAIRED: 'funnel_daemon_paired',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FUNNEL_FIRST_GAME_PLAYED: 'funnel_first_game_played',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FUNNEL_FIRST_DATA_LOADED: 'funnel_first_data_loaded',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FUNNEL_FIRST_FEATURE_USED: 'funnel_first_feature_used',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FEATURE_DRAFT_ADVISOR_PICK_VIEWED: 'feature_draft_advisor_pick_viewed',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FEATURE_DRAFT_ANALYTICS_VIEWED: 'feature_draft_analytics_viewed',
  /** Category: match | Surface: spa | Consent: analytics */
  FEATURE_MATCH_HISTORY_FILTERED: 'feature_match_history_filtered',
  /** Category: collection | Surface: spa | Consent: analytics */
  FEATURE_COLLECTION_VIEWED: 'feature_collection_viewed',
  /** Category: feature_use | Surface: spa | Consent: analytics */
  FEATURE_SETTINGS_CHANGED: 'feature_settings_changed',
  /** Category: wildcard | Surface: spa | Consent: analytics */
  WILDCARD_RECOMMENDATION_CLICKED: 'wildcard_recommendation_clicked',
  /** Category: error | Surface: spa | Consent: necessary */
  ERROR_DAEMON_CONNECTION_FAILED: 'error_daemon_connection_failed',
  /** Category: error | Surface: spa | Consent: necessary */
  ERROR_DATA_LOAD_FAILED: 'error_data_load_failed',
  /** Category: error | Surface: spa | Consent: necessary */
  ERROR_AUTH_FAILED: 'error_auth_failed',
  /** Category: system | Surface: bff | Consent: necessary */
  DAEMON_EVENT_GAP_DETECTED: 'daemon_event_gap_detected',
  /** Category: system | Surface: bff | Consent: necessary */
  DAEMON_DISPATCH_DEGRADED: 'daemon_dispatch_degraded',
  /** Category: system | Surface: bff | Consent: necessary */
  DAEMON_AUTH_FAILED: 'daemon_auth_failed',
  /** Category: system | Surface: bff | Consent: necessary */
  DAEMON_KEYCHAIN_ERROR: 'daemon_keychain_error',
  /** Category: system | Surface: bff | Consent: necessary */
  DAEMON_ACCOUNT_ID_MISMATCH: 'daemon_account_id_mismatch',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  GET_DECK: 'get_deck',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  CREATE_DECK: 'create_deck',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  UPDATE_DECK: 'update_deck',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  DELETE_DECK: 'delete_deck',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  CLONE_DECK: 'clone_deck',
  /** Category: feature_use | Surface: bff | Consent: analytics */
  EXPORT_DECK: 'export_deck',
} as const;

export type EventName = (typeof Events)[keyof typeof Events];

/**
 * ConsentCategory maps each event name to its required consent tier.
 * The SPA PostHog gate reads this map to decide which events to drop
 * when the user has not given analytics consent.
 *   - 'necessary'  — fires regardless of consent (auth events, error events)
 *   - 'analytics'  — requires analytics consent
 *   - 'marketing'  — reserved for future use
 */
export type ConsentCategory = 'necessary' | 'analytics' | 'marketing';

export const EventConsentCategory: Record<EventName, ConsentCategory> = {
  'page_viewed': 'analytics',
  'app_session_started': 'analytics',
  'app_user_identified': 'necessary',
  'app_user_signed_out': 'necessary',
  'funnel_sign_up_started': 'analytics',
  'funnel_sign_up_completed': 'analytics',
  'funnel_daemon_download_started': 'analytics',
  'funnel_daemon_connected': 'analytics',
  'funnel_daemon_paired': 'analytics',
  'funnel_first_game_played': 'analytics',
  'funnel_first_data_loaded': 'analytics',
  'funnel_first_feature_used': 'analytics',
  'feature_draft_advisor_pick_viewed': 'analytics',
  'feature_draft_analytics_viewed': 'analytics',
  'feature_match_history_filtered': 'analytics',
  'feature_collection_viewed': 'analytics',
  'feature_settings_changed': 'analytics',
  'wildcard_recommendation_clicked': 'analytics',
  'error_daemon_connection_failed': 'necessary',
  'error_data_load_failed': 'necessary',
  'error_auth_failed': 'necessary',
  'daemon_event_gap_detected': 'necessary',
  'daemon_dispatch_degraded': 'necessary',
  'daemon_auth_failed': 'necessary',
  'daemon_keychain_error': 'necessary',
  'daemon_account_id_mismatch': 'necessary',
  'get_deck': 'analytics',
  'create_deck': 'analytics',
  'update_deck': 'analytics',
  'delete_deck': 'analytics',
  'clone_deck': 'analytics',
  'export_deck': 'analytics',
};

/**
 * CMPStorageKey is the localStorage key written by the SPA's own PostHog-consent
 * surface (NOT the cookie consent banner #877 — that is a separate independent
 * flow).  It is the single authoritative source — never hard-code this string
 * elsewhere.  Stays vaultmtg_* per INVARIANTS I-57 until the v0.4.x cutover.
 */
export const CMPStorageKey = 'vaultmtg_consent_v1';
