//go:build ignore

// gen-analytics-taxonomy.go generates services/bff/internal/analytics/taxonomy.gen.go
// from services/bff/internal/analytics/taxonomy.yml.
//
// Usage:
//
//	go run scripts/gen-analytics-taxonomy.go              # writes file in-place
//	go run scripts/gen-analytics-taxonomy.go --stdout     # prints to stdout (for staleness check)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
	"time"

	"gopkg.in/yaml.v3"
)

const goTmpl = `// Code generated by scripts/gen-analytics-taxonomy.go — DO NOT EDIT.
// Source: services/bff/internal/analytics/taxonomy.yml
// Generated: {{ .Timestamp }}

package analytics

// Event name constants generated from taxonomy.yml.
// All BFF PostHog emitters MUST use these constants for event names.
const (
{{- range .Events }}
	// {{ .ConstName }} corresponds to the "{{ .Name }}" PostHog event.
	// Category: {{ .Category }} | Surface: {{ .TriggerSurface }} | Consent: {{ .ConsentCategory }}
	{{ .ConstName }} = "{{ .Name }}"
{{ end -}}
)
`

type property struct {
	Name        string `yaml:"name"`
	Type        string `yaml:"type"`
	PIIClass    string `yaml:"pii_class"`
	Description string `yaml:"description,omitempty"`
}

type event struct {
	Name            string     `yaml:"name"`
	Category        string     `yaml:"category"`
	TriggerSurface  string     `yaml:"trigger_surface"`
	ConsentCategory string     `yaml:"consent_category"`
	Properties      []property `yaml:"properties"`
}

type taxonomy struct {
	Version      string  `yaml:"version"`
	CMPStorageKey string `yaml:"cmp_storage_key"`
	Events       []event `yaml:"events"`
}

type templateEvent struct {
	Name            string
	ConstName       string
	Category        string
	TriggerSurface  string
	ConsentCategory string
}

type templateData struct {
	Timestamp string
	Events    []templateEvent
}

func toConstName(name string) string {
	// snake_case → SCREAMING_SNAKE_CASE prefixed with "Event"
	parts := strings.Split(name, "_")
	var out strings.Builder
	out.WriteString("Event")
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		out.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			out.WriteString(p[1:])
		}
	}
	return out.String()
}

func run() error {
	stdout := flag.Bool("stdout", false, "write to stdout instead of the generated file")
	flag.Parse()

	// Locate the repo root relative to this script file.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		return fmt.Errorf("runtime.Caller(0) failed")
	}
	// thisFile = .../scripts/gen-analytics-taxonomy.go  → repoRoot = parent
	repoRoot := filepath.Dir(filepath.Dir(thisFile))

	yamlPath := filepath.Join(repoRoot, "services", "bff", "internal", "analytics", "taxonomy.yml")
	raw, err := os.ReadFile(yamlPath)
	if err != nil {
		return fmt.Errorf("read taxonomy.yml: %w", err)
	}

	var tax taxonomy
	if err := yaml.Unmarshal(raw, &tax); err != nil {
		return fmt.Errorf("parse taxonomy.yml: %w", err)
	}

	// Guard: reject pii_raw_FORBIDDEN at codegen time.
	for _, ev := range tax.Events {
		for _, prop := range ev.Properties {
			if prop.PIIClass == "pii_raw_FORBIDDEN" {
				return fmt.Errorf("codegen rejected: event %q property %q has pii_class pii_raw_FORBIDDEN — raw PII must never leave the process", ev.Name, prop.Name)
			}
		}
	}

	tmplEvents := make([]templateEvent, 0, len(tax.Events))
	for _, ev := range tax.Events {
		tmplEvents = append(tmplEvents, templateEvent{
			Name:            ev.Name,
			ConstName:       toConstName(ev.Name),
			Category:        ev.Category,
			TriggerSurface:  ev.TriggerSurface,
			ConsentCategory: ev.ConsentCategory,
		})
	}

	data := templateData{
		Timestamp: time.Now().UTC().Format("2006-01-02"),
		Events:    tmplEvents,
	}

	tmpl, err := template.New("go").Parse(goTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	if *stdout {
		_, err = os.Stdout.Write(buf.Bytes())
		return err
	}

	outPath := filepath.Join(repoRoot, "services", "bff", "internal", "analytics", "taxonomy.gen.go")
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s\n", outPath)
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-analytics-taxonomy: %v\n", err)
		os.Exit(1)
	}
}
