#!/usr/bin/env tsx
/**
 * gen-analytics-taxonomy.ts
 *
 * Generates frontend/src/services/analytics-taxonomy.gen.ts from
 * services/bff/internal/analytics/taxonomy.yml.
 *
 * Usage:
 *   npx tsx scripts/gen-analytics-taxonomy.ts           # writes file in-place
 *   npx tsx scripts/gen-analytics-taxonomy.ts --stdout  # prints to stdout (staleness check)
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';

// Minimal YAML parser for our well-structured taxonomy file.
// We use the yaml package available in the frontend node_modules.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const yaml = require(
  path.resolve(__dirname, '../frontend/node_modules/js-yaml'),
) as typeof import('js-yaml');

interface TaxonomyProperty {
  name: string;
  type: string;
  pii_class: string;
  description?: string;
}

interface TaxonomyEvent {
  name: string;
  category: string;
  trigger_surface: string;
  consent_category: string;
  properties: TaxonomyProperty[];
}

interface Taxonomy {
  version: string;
  cmp_storage_key: string;
  events: TaxonomyEvent[];
}

function toTSConstKey(name: string): string {
  // snake_case → SCREAMING_SNAKE_CASE
  return name.toUpperCase();
}

function generate(tax: Taxonomy, timestamp: string): string {
  // Guard: reject pii_raw_FORBIDDEN at codegen time.
  for (const ev of tax.events) {
    for (const prop of ev.properties) {
      if (prop.pii_class === 'pii_raw_FORBIDDEN') {
        throw new Error(
          `codegen rejected: event "${ev.name}" property "${prop.name}" has pii_class pii_raw_FORBIDDEN — raw PII must never leave the process`,
        );
      }
    }
  }

  const eventsConst = tax.events
    .map(
      (ev) =>
        `  /** Category: ${ev.category} | Surface: ${ev.trigger_surface} | Consent: ${ev.consent_category} */\n` +
        `  ${toTSConstKey(ev.name)}: '${ev.name}',`,
    )
    .join('\n');

  const consentMap = tax.events
    .map((ev) => `  '${ev.name}': '${ev.consent_category}',`)
    .join('\n');

  return `// Code generated by scripts/gen-analytics-taxonomy.ts — DO NOT EDIT.
// Source: services/bff/internal/analytics/taxonomy.yml
// Generated: ${timestamp}

/**
 * Generated PostHog event name constants from taxonomy.yml.
 * All SPA PostHog emitters MUST use these constants for event names.
 * Do not hand-edit — run \`make gen-taxonomy\` to regenerate.
 */
export const Events = {
${eventsConst}
} as const;

export type EventName = (typeof Events)[keyof typeof Events];

/**
 * ConsentCategory maps each event name to its required consent tier.
 * Frank's #877 consent banner reads this map to decide which events to drop
 * when the user has not given analytics consent.
 *   - 'necessary'  — fires regardless of consent (auth events, error events)
 *   - 'analytics'  — requires analytics consent
 *   - 'marketing'  — reserved for future use
 */
export type ConsentCategory = 'necessary' | 'analytics' | 'marketing';

export const EventConsentCategory: Record<EventName, ConsentCategory> = {
${consentMap}
};

/**
 * CMPStorageKey is the localStorage key written by the cookie consent banner
 * (#877).  It is the single authoritative source — never hard-code this string
 * elsewhere.  Stays vaultmtg_* per INVARIANTS I-57 until the v0.4.x cutover.
 */
export const CMPStorageKey = '${tax.cmp_storage_key}';
`;
}

function main(): void {
  const toStdout = process.argv.includes('--stdout');

  // Locate repo root relative to this script.
  const repoRoot = path.resolve(__dirname, '..');
  const yamlPath = path.join(
    repoRoot,
    'services',
    'bff',
    'internal',
    'analytics',
    'taxonomy.yml',
  );

  const raw = fs.readFileSync(yamlPath, 'utf8');
  const tax = yaml.load(raw) as Taxonomy;

  const timestamp = new Date().toISOString().slice(0, 10);
  const output = generate(tax, timestamp);

  if (toStdout) {
    process.stdout.write(output);
    return;
  }

  const outPath = path.join(
    repoRoot,
    'frontend',
    'src',
    'services',
    'analytics-taxonomy.gen.ts',
  );
  fs.writeFileSync(outPath, output, 'utf8');
  console.log(`wrote ${outPath}`);
}

main();
