// Code generated by scripts/gen-analytics-taxonomy.go — DO NOT EDIT.
// Source: services/bff/internal/analytics/taxonomy.yml
// Generated: 2026-06-11

package analytics

// Event name constants generated from taxonomy.yml.
// All BFF PostHog emitters MUST use these constants for event names.
const (
	// EventPageViewed corresponds to the "page_viewed" PostHog event.
	// Category: nav | Surface: spa | Consent: analytics
	EventPageViewed = "page_viewed"

	// EventAppSessionStarted corresponds to the "app_session_started" PostHog event.
	// Category: nav | Surface: spa | Consent: analytics
	EventAppSessionStarted = "app_session_started"

	// EventAppUserIdentified corresponds to the "app_user_identified" PostHog event.
	// Category: auth | Surface: spa | Consent: necessary
	EventAppUserIdentified = "app_user_identified"

	// EventAppUserSignedOut corresponds to the "app_user_signed_out" PostHog event.
	// Category: auth | Surface: spa | Consent: necessary
	EventAppUserSignedOut = "app_user_signed_out"

	// EventFunnelSignUpStarted corresponds to the "funnel_sign_up_started" PostHog event.
	// Category: auth | Surface: spa | Consent: analytics
	EventFunnelSignUpStarted = "funnel_sign_up_started"

	// EventFunnelSignUpCompleted corresponds to the "funnel_sign_up_completed" PostHog event.
	// Category: auth | Surface: spa | Consent: analytics
	EventFunnelSignUpCompleted = "funnel_sign_up_completed"

	// EventFunnelDaemonDownloadStarted corresponds to the "funnel_daemon_download_started" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFunnelDaemonDownloadStarted = "funnel_daemon_download_started"

	// EventFunnelDaemonConnected corresponds to the "funnel_daemon_connected" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFunnelDaemonConnected = "funnel_daemon_connected"

	// EventFunnelDaemonPaired corresponds to the "funnel_daemon_paired" PostHog event.
	// Category: feature_use | Surface: bff | Consent: analytics
	EventFunnelDaemonPaired = "funnel_daemon_paired"

	// EventFunnelFirstGamePlayed corresponds to the "funnel_first_game_played" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFunnelFirstGamePlayed = "funnel_first_game_played"

	// EventFunnelFirstDataLoaded corresponds to the "funnel_first_data_loaded" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFunnelFirstDataLoaded = "funnel_first_data_loaded"

	// EventFunnelFirstFeatureUsed corresponds to the "funnel_first_feature_used" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFunnelFirstFeatureUsed = "funnel_first_feature_used"

	// EventFeatureDraftAdvisorPickViewed corresponds to the "feature_draft_advisor_pick_viewed" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFeatureDraftAdvisorPickViewed = "feature_draft_advisor_pick_viewed"

	// EventFeatureDraftAnalyticsViewed corresponds to the "feature_draft_analytics_viewed" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFeatureDraftAnalyticsViewed = "feature_draft_analytics_viewed"

	// EventFeatureMatchHistoryFiltered corresponds to the "feature_match_history_filtered" PostHog event.
	// Category: match | Surface: spa | Consent: analytics
	EventFeatureMatchHistoryFiltered = "feature_match_history_filtered"

	// EventFeatureCollectionViewed corresponds to the "feature_collection_viewed" PostHog event.
	// Category: collection | Surface: spa | Consent: analytics
	EventFeatureCollectionViewed = "feature_collection_viewed"

	// EventFeatureSettingsChanged corresponds to the "feature_settings_changed" PostHog event.
	// Category: feature_use | Surface: spa | Consent: analytics
	EventFeatureSettingsChanged = "feature_settings_changed"

	// EventWildcardRecommendationClicked corresponds to the "wildcard_recommendation_clicked" PostHog event.
	// Category: wildcard | Surface: spa | Consent: analytics
	EventWildcardRecommendationClicked = "wildcard_recommendation_clicked"

	// EventErrorDaemonConnectionFailed corresponds to the "error_daemon_connection_failed" PostHog event.
	// Category: error | Surface: spa | Consent: necessary
	EventErrorDaemonConnectionFailed = "error_daemon_connection_failed"

	// EventErrorDataLoadFailed corresponds to the "error_data_load_failed" PostHog event.
	// Category: error | Surface: spa | Consent: necessary
	EventErrorDataLoadFailed = "error_data_load_failed"

	// EventErrorAuthFailed corresponds to the "error_auth_failed" PostHog event.
	// Category: error | Surface: spa | Consent: necessary
	EventErrorAuthFailed = "error_auth_failed"

	// EventDaemonEventGapDetected corresponds to the "daemon_event_gap_detected" PostHog event.
	// Category: system | Surface: bff | Consent: necessary
	EventDaemonEventGapDetected = "daemon_event_gap_detected"

	// EventDaemonDispatchDegraded corresponds to the "daemon_dispatch_degraded" PostHog event.
	// Category: system | Surface: bff | Consent: necessary
	EventDaemonDispatchDegraded = "daemon_dispatch_degraded"

	// EventDaemonAuthFailed corresponds to the "daemon_auth_failed" PostHog event.
	// Category: system | Surface: bff | Consent: necessary
	EventDaemonAuthFailed = "daemon_auth_failed"

	// EventDaemonKeychainError corresponds to the "daemon_keychain_error" PostHog event.
	// Category: system | Surface: bff | Consent: necessary
	EventDaemonKeychainError = "daemon_keychain_error"
)
