// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCard'](arg1, arg2, arg3, arg4, arg5);
}

export function AddTag(arg1, arg2) {
  return window['go']['main']['App']['AddTag'](arg1, arg2);
}

export function AnalyzeSessionPickQuality(arg1) {
  return window['go']['main']['App']['AnalyzeSessionPickQuality'](arg1);
}

export function CalculateDraftGrade(arg1) {
  return window['go']['main']['App']['CalculateDraftGrade'](arg1);
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ClearDatasetCache() {
  return window['go']['main']['App']['ClearDatasetCache']();
}

export function CloneDeck(arg1, arg2) {
  return window['go']['main']['App']['CloneDeck'](arg1, arg2);
}

export function CreateDeck(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDeck'](arg1, arg2, arg3, arg4);
}

export function DeleteDeck(arg1) {
  return window['go']['main']['App']['DeleteDeck'](arg1);
}

export function ExplainRecommendation(arg1) {
  return window['go']['main']['App']['ExplainRecommendation'](arg1);
}

export function ExportDeck(arg1) {
  return window['go']['main']['App']['ExportDeck'](arg1);
}

export function ExportDeckToFile(arg1) {
  return window['go']['main']['App']['ExportDeckToFile'](arg1);
}

export function ExportToCSV() {
  return window['go']['main']['App']['ExportToCSV']();
}

export function ExportToJSON() {
  return window['go']['main']['App']['ExportToJSON']();
}

export function FetchSetCards(arg1) {
  return window['go']['main']['App']['FetchSetCards'](arg1);
}

export function FetchSetRatings(arg1, arg2) {
  return window['go']['main']['App']['FetchSetRatings'](arg1, arg2);
}

export function FixDraftSessionStatuses() {
  return window['go']['main']['App']['FixDraftSessionStatuses']();
}

export function GetAchievementUpdatedEvent() {
  return window['go']['main']['App']['GetAchievementUpdatedEvent']();
}

export function GetActiveDraftSessions() {
  return window['go']['main']['App']['GetActiveDraftSessions']();
}

export function GetActiveEvents() {
  return window['go']['main']['App']['GetActiveEvents']();
}

export function GetActiveQuests() {
  return window['go']['main']['App']['GetActiveQuests']();
}

export function GetAllSetInfo() {
  return window['go']['main']['App']['GetAllSetInfo']();
}

export function GetArchetypeCards(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetArchetypeCards'](arg1, arg2, arg3);
}

export function GetCardByArenaID(arg1) {
  return window['go']['main']['App']['GetCardByArenaID'](arg1);
}

export function GetCardRatingByArenaID(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCardRatingByArenaID'](arg1, arg2, arg3);
}

export function GetCardRatings(arg1, arg2) {
  return window['go']['main']['App']['GetCardRatings'](arg1, arg2);
}

export function GetColorRatings(arg1, arg2) {
  return window['go']['main']['App']['GetColorRatings'](arg1, arg2);
}

export function GetCompletedDraftSessions(arg1) {
  return window['go']['main']['App']['GetCompletedDraftSessions'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentAccount() {
  return window['go']['main']['App']['GetCurrentAccount']();
}

export function GetDaemonErrorEvent() {
  return window['go']['main']['App']['GetDaemonErrorEvent']();
}

export function GetDatasetSource(arg1, arg2) {
  return window['go']['main']['App']['GetDatasetSource'](arg1, arg2);
}

export function GetDeck(arg1) {
  return window['go']['main']['App']['GetDeck'](arg1);
}

export function GetDeckByDraftEvent(arg1) {
  return window['go']['main']['App']['GetDeckByDraftEvent'](arg1);
}

export function GetDeckLibrary(arg1) {
  return window['go']['main']['App']['GetDeckLibrary'](arg1);
}

export function GetDeckPerformance(arg1) {
  return window['go']['main']['App']['GetDeckPerformance'](arg1);
}

export function GetDeckStatistics(arg1) {
  return window['go']['main']['App']['GetDeckStatistics'](arg1);
}

export function GetDeckUpdatedEvent() {
  return window['go']['main']['App']['GetDeckUpdatedEvent']();
}

export function GetDecksByFormat(arg1) {
  return window['go']['main']['App']['GetDecksByFormat'](arg1);
}

export function GetDecksBySource(arg1) {
  return window['go']['main']['App']['GetDecksBySource'](arg1);
}

export function GetDecksByTags(arg1) {
  return window['go']['main']['App']['GetDecksByTags'](arg1);
}

export function GetDraftDeckMetrics(arg1) {
  return window['go']['main']['App']['GetDraftDeckMetrics'](arg1);
}

export function GetDraftGrade(arg1) {
  return window['go']['main']['App']['GetDraftGrade'](arg1);
}

export function GetDraftPacks(arg1) {
  return window['go']['main']['App']['GetDraftPacks'](arg1);
}

export function GetDraftPerformanceMetrics() {
  return window['go']['main']['App']['GetDraftPerformanceMetrics']();
}

export function GetDraftPicks(arg1) {
  return window['go']['main']['App']['GetDraftPicks'](arg1);
}

export function GetDraftSession(arg1) {
  return window['go']['main']['App']['GetDraftSession'](arg1);
}

export function GetDraftUpdatedEvent() {
  return window['go']['main']['App']['GetDraftUpdatedEvent']();
}

export function GetDraftWinRatePrediction(arg1) {
  return window['go']['main']['App']['GetDraftWinRatePrediction'](arg1);
}

export function GetEventWinDistribution() {
  return window['go']['main']['App']['GetEventWinDistribution']();
}

export function GetFormatInsights(arg1, arg2) {
  return window['go']['main']['App']['GetFormatInsights'](arg1, arg2);
}

export function GetLogReplayProgress() {
  return window['go']['main']['App']['GetLogReplayProgress']();
}

export function GetMatchGames(arg1) {
  return window['go']['main']['App']['GetMatchGames'](arg1);
}

export function GetMatches(arg1) {
  return window['go']['main']['App']['GetMatches'](arg1);
}

export function GetMissingCards(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMissingCards'](arg1, arg2, arg3);
}

export function GetPerformanceMetrics(arg1) {
  return window['go']['main']['App']['GetPerformanceMetrics'](arg1);
}

export function GetPickAlternatives(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPickAlternatives'](arg1, arg2, arg3);
}

export function GetQuestHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetQuestHistory'](arg1, arg2, arg3);
}

export function GetQuestStats(arg1, arg2) {
  return window['go']['main']['App']['GetQuestStats'](arg1, arg2);
}

export function GetQuestUpdatedEvent() {
  return window['go']['main']['App']['GetQuestUpdatedEvent']();
}

export function GetRankProgression(arg1) {
  return window['go']['main']['App']['GetRankProgression'](arg1);
}

export function GetRankProgressionTimeline(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRankProgressionTimeline'](arg1, arg2, arg3, arg4);
}

export function GetRankUpdatedEvent() {
  return window['go']['main']['App']['GetRankUpdatedEvent']();
}

export function GetRecommendations(arg1) {
  return window['go']['main']['App']['GetRecommendations'](arg1);
}

export function GetReplayDraftDetectedEvent() {
  return window['go']['main']['App']['GetReplayDraftDetectedEvent']();
}

export function GetReplayErrorEvent() {
  return window['go']['main']['App']['GetReplayErrorEvent']();
}

export function GetReplayStatus() {
  return window['go']['main']['App']['GetReplayStatus']();
}

export function GetSetCards(arg1) {
  return window['go']['main']['App']['GetSetCards'](arg1);
}

export function GetSetInfo(arg1) {
  return window['go']['main']['App']['GetSetInfo'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStatsByDeck(arg1) {
  return window['go']['main']['App']['GetStatsByDeck'](arg1);
}

export function GetStatsByFormat(arg1) {
  return window['go']['main']['App']['GetStatsByFormat'](arg1);
}

export function GetStatsUpdatedEvent() {
  return window['go']['main']['App']['GetStatsUpdatedEvent']();
}

export function GetTrendAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTrendAnalysis'](arg1, arg2, arg3, arg4);
}

export function ImportDeck(arg1) {
  return window['go']['main']['App']['ImportDeck'](arg1);
}

export function ImportFromFile() {
  return window['go']['main']['App']['ImportFromFile']();
}

export function ImportLogFile() {
  return window['go']['main']['App']['ImportLogFile']();
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function ListDecks() {
  return window['go']['main']['App']['ListDecks']();
}

export function PauseReplay() {
  return window['go']['main']['App']['PauseReplay']();
}

export function PredictDraftWinRate(arg1) {
  return window['go']['main']['App']['PredictDraftWinRate'](arg1);
}

export function RecalculateAllDraftGrades() {
  return window['go']['main']['App']['RecalculateAllDraftGrades']();
}

export function ReconnectToDaemon() {
  return window['go']['main']['App']['ReconnectToDaemon']();
}

export function RefreshSetCards(arg1) {
  return window['go']['main']['App']['RefreshSetCards'](arg1);
}

export function RefreshSetRatings(arg1, arg2) {
  return window['go']['main']['App']['RefreshSetRatings'](arg1, arg2);
}

export function RemoveCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveCard'](arg1, arg2, arg3);
}

export function RemoveTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveTag'](arg1, arg2);
}

export function RepairDraftSession(arg1) {
  return window['go']['main']['App']['RepairDraftSession'](arg1);
}

export function ResetDraftPerformanceMetrics() {
  return window['go']['main']['App']['ResetDraftPerformanceMetrics']();
}

export function ResumeReplay() {
  return window['go']['main']['App']['ResumeReplay']();
}

export function SetDaemonPort(arg1) {
  return window['go']['main']['App']['SetDaemonPort'](arg1);
}

export function StartPoller() {
  return window['go']['main']['App']['StartPoller']();
}

export function StartReplayWithFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartReplayWithFileDialog'](arg1, arg2, arg3);
}

export function StopPoller() {
  return window['go']['main']['App']['StopPoller']();
}

export function StopReplay() {
  return window['go']['main']['App']['StopReplay']();
}

export function SwitchToDaemonMode() {
  return window['go']['main']['App']['SwitchToDaemonMode']();
}

export function SwitchToStandaloneMode() {
  return window['go']['main']['App']['SwitchToStandaloneMode']();
}

export function TriggerReplayLogs(arg1) {
  return window['go']['main']['App']['TriggerReplayLogs'](arg1);
}

export function UpdateDeck(arg1) {
  return window['go']['main']['App']['UpdateDeck'](arg1);
}

export function ValidateDeckWithDialog(arg1) {
  return window['go']['main']['App']['ValidateDeckWithDialog'](arg1);
}

export function ValidateDraftDeck(arg1) {
  return window['go']['main']['App']['ValidateDraftDeck'](arg1);
}
