// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAchievementStats() {
  return window['go']['main']['App']['GetAchievementStats']();
}

export function GetAchievementsByStatus(arg1) {
  return window['go']['main']['App']['GetAchievementsByStatus'](arg1);
}

export function GetActiveQuests() {
  return window['go']['main']['App']['GetActiveQuests']();
}

export function GetAllAchievements() {
  return window['go']['main']['App']['GetAllAchievements']();
}

export function GetCloseToCompleteAchievements() {
  return window['go']['main']['App']['GetCloseToCompleteAchievements']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetMatches(arg1) {
  return window['go']['main']['App']['GetMatches'](arg1);
}

export function GetPerformanceMetrics(arg1) {
  return window['go']['main']['App']['GetPerformanceMetrics'](arg1);
}

export function GetQuestHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetQuestHistory'](arg1, arg2, arg3);
}

export function GetQuestStats(arg1, arg2) {
  return window['go']['main']['App']['GetQuestStats'](arg1, arg2);
}

export function GetRankProgression(arg1) {
  return window['go']['main']['App']['GetRankProgression'](arg1);
}

export function GetRankProgressionTimeline(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRankProgressionTimeline'](arg1, arg2, arg3, arg4);
}

export function GetRecentlyCompletedAchievements(arg1) {
  return window['go']['main']['App']['GetRecentlyCompletedAchievements'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStatsByDeck(arg1) {
  return window['go']['main']['App']['GetStatsByDeck'](arg1);
}

export function GetStatsByFormat(arg1) {
  return window['go']['main']['App']['GetStatsByFormat'](arg1);
}

export function GetTrendAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTrendAnalysis'](arg1, arg2, arg3, arg4);
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function ReconnectToDaemon() {
  return window['go']['main']['App']['ReconnectToDaemon']();
}

export function SetDaemonPort(arg1) {
  return window['go']['main']['App']['SetDaemonPort'](arg1);
}

export function StartPoller() {
  return window['go']['main']['App']['StartPoller']();
}

export function StopPoller() {
  return window['go']['main']['App']['StopPoller']();
}

export function SwitchToDaemonMode() {
  return window['go']['main']['App']['SwitchToDaemonMode']();
}

export function SwitchToStandaloneMode() {
  return window['go']['main']['App']['SwitchToStandaloneMode']();
}
