// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSessionPickQuality(arg1) {
  return window['go']['main']['App']['AnalyzeSessionPickQuality'](arg1);
}

export function CalculateDraftGrade(arg1) {
  return window['go']['main']['App']['CalculateDraftGrade'](arg1);
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ExportToCSV() {
  return window['go']['main']['App']['ExportToCSV']();
}

export function ExportToJSON() {
  return window['go']['main']['App']['ExportToJSON']();
}

export function FetchSetCards(arg1) {
  return window['go']['main']['App']['FetchSetCards'](arg1);
}

export function FetchSetRatings(arg1, arg2) {
  return window['go']['main']['App']['FetchSetRatings'](arg1, arg2);
}

export function FixDraftSessionStatuses() {
  return window['go']['main']['App']['FixDraftSessionStatuses']();
}

export function GetActiveDraftSessions() {
  return window['go']['main']['App']['GetActiveDraftSessions']();
}

export function GetActiveEvents() {
  return window['go']['main']['App']['GetActiveEvents']();
}

export function GetActiveQuests() {
  return window['go']['main']['App']['GetActiveQuests']();
}

export function GetCardByArenaID(arg1) {
  return window['go']['main']['App']['GetCardByArenaID'](arg1);
}

export function GetCardRatingByArenaID(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCardRatingByArenaID'](arg1, arg2, arg3);
}

export function GetCardRatings(arg1, arg2) {
  return window['go']['main']['App']['GetCardRatings'](arg1, arg2);
}

export function GetColorRatings(arg1, arg2) {
  return window['go']['main']['App']['GetColorRatings'](arg1, arg2);
}

export function GetCompletedDraftSessions(arg1) {
  return window['go']['main']['App']['GetCompletedDraftSessions'](arg1);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentAccount() {
  return window['go']['main']['App']['GetCurrentAccount']();
}

export function GetDraftGrade(arg1) {
  return window['go']['main']['App']['GetDraftGrade'](arg1);
}

export function GetDraftPacks(arg1) {
  return window['go']['main']['App']['GetDraftPacks'](arg1);
}

export function GetDraftPicks(arg1) {
  return window['go']['main']['App']['GetDraftPicks'](arg1);
}

export function GetDraftSession(arg1) {
  return window['go']['main']['App']['GetDraftSession'](arg1);
}

export function GetDraftWinRatePrediction(arg1) {
  return window['go']['main']['App']['GetDraftWinRatePrediction'](arg1);
}

export function GetEventWinDistribution() {
  return window['go']['main']['App']['GetEventWinDistribution']();
}

export function GetMatches(arg1) {
  return window['go']['main']['App']['GetMatches'](arg1);
}

export function GetPerformanceMetrics(arg1) {
  return window['go']['main']['App']['GetPerformanceMetrics'](arg1);
}

export function GetPickAlternatives(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPickAlternatives'](arg1, arg2, arg3);
}

export function GetQuestHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetQuestHistory'](arg1, arg2, arg3);
}

export function GetQuestStats(arg1, arg2) {
  return window['go']['main']['App']['GetQuestStats'](arg1, arg2);
}

export function GetRankProgression(arg1) {
  return window['go']['main']['App']['GetRankProgression'](arg1);
}

export function GetRankProgressionTimeline(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRankProgressionTimeline'](arg1, arg2, arg3, arg4);
}

export function GetSetCards(arg1) {
  return window['go']['main']['App']['GetSetCards'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStatsByDeck(arg1) {
  return window['go']['main']['App']['GetStatsByDeck'](arg1);
}

export function GetStatsByFormat(arg1) {
  return window['go']['main']['App']['GetStatsByFormat'](arg1);
}

export function GetTrendAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTrendAnalysis'](arg1, arg2, arg3, arg4);
}

export function ImportFromFile() {
  return window['go']['main']['App']['ImportFromFile']();
}

export function ImportLogFile() {
  return window['go']['main']['App']['ImportLogFile']();
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function PredictDraftWinRate(arg1) {
  return window['go']['main']['App']['PredictDraftWinRate'](arg1);
}

export function ReconnectToDaemon() {
  return window['go']['main']['App']['ReconnectToDaemon']();
}

export function RefreshSetCards(arg1) {
  return window['go']['main']['App']['RefreshSetCards'](arg1);
}

export function RefreshSetRatings(arg1, arg2) {
  return window['go']['main']['App']['RefreshSetRatings'](arg1, arg2);
}

export function SetDaemonPort(arg1) {
  return window['go']['main']['App']['SetDaemonPort'](arg1);
}

export function StartPoller() {
  return window['go']['main']['App']['StartPoller']();
}

export function StopPoller() {
  return window['go']['main']['App']['StopPoller']();
}

export function SwitchToDaemonMode() {
  return window['go']['main']['App']['SwitchToDaemonMode']();
}

export function SwitchToStandaloneMode() {
  return window['go']['main']['App']['SwitchToStandaloneMode']();
}

export function TriggerReplayLogs(arg1) {
  return window['go']['main']['App']['TriggerReplayLogs'](arg1);
}
