// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';
import {storage} from '../models';

export function GetMatches(arg1:models.StatsFilter):Promise<Array<models.Match>>;

export function GetPerformanceMetrics(arg1:models.StatsFilter):Promise<models.PerformanceMetrics>;

export function GetRankProgression(arg1:string):Promise<models.RankProgression>;

export function GetRankProgressionTimeline(arg1:string,arg2:time.Time,arg3:time.Time,arg4:storage.TimelinePeriod):Promise<storage.RankTimeline>;

export function GetStats(arg1:models.StatsFilter):Promise<models.Statistics>;

export function GetStatsByDeck(arg1:models.StatsFilter):Promise<Record<string, models.Statistics>>;

export function GetStatsByFormat(arg1:models.StatsFilter):Promise<Record<string, models.Statistics>>;

export function GetTrendAnalysis(arg1:time.Time,arg2:time.Time,arg3:string,arg4:Array<string>):Promise<storage.TrendAnalysis>;

export function Initialize(arg1:string):Promise<void>;
