// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {grading} from '../models';
import {models} from '../models';
import {main} from '../models';
import {seventeenlands} from '../models';
import {prediction} from '../models';
import {storage} from '../models';
import {pickquality} from '../models';
import {time} from '../models';

export function AnalyzeSessionPickQuality(arg1:string):Promise<void>;

export function CalculateDraftGrade(arg1:string):Promise<grading.DraftGrade>;

export function ClearAllData():Promise<void>;

export function ClearDatasetCache():Promise<void>;

export function ExportToCSV():Promise<void>;

export function ExportToJSON():Promise<void>;

export function FetchSetCards(arg1:string):Promise<number>;

export function FetchSetRatings(arg1:string,arg2:string):Promise<void>;

export function FixDraftSessionStatuses():Promise<number>;

export function GetActiveDraftSessions():Promise<Array<models.DraftSession>>;

export function GetActiveEvents():Promise<Array<models.DraftEvent>>;

export function GetActiveQuests():Promise<Array<models.Quest>>;

export function GetCardByArenaID(arg1:string):Promise<models.SetCard>;

export function GetCardRatingByArenaID(arg1:string,arg2:string,arg3:string):Promise<main.CardRatingWithTier>;

export function GetCardRatings(arg1:string,arg2:string):Promise<Array<main.CardRatingWithTier>>;

export function GetColorRatings(arg1:string,arg2:string):Promise<Array<seventeenlands.ColorRating>>;

export function GetCompletedDraftSessions(arg1:number):Promise<Array<models.DraftSession>>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetCurrentAccount():Promise<models.Account>;

export function GetDatasetSource(arg1:string,arg2:string):Promise<string>;

export function GetDraftGrade(arg1:string):Promise<grading.DraftGrade>;

export function GetDraftPacks(arg1:string):Promise<Array<models.DraftPackSession>>;

export function GetDraftPicks(arg1:string):Promise<Array<models.DraftPickSession>>;

export function GetDraftSession(arg1:string):Promise<models.DraftSession>;

export function GetDraftWinRatePrediction(arg1:string):Promise<prediction.DeckPrediction>;

export function GetEventWinDistribution():Promise<Array<storage.EventWinDistribution>>;

export function GetMatches(arg1:models.StatsFilter):Promise<Array<models.Match>>;

export function GetMissingCards(arg1:string,arg2:number,arg3:number):Promise<models.MissingCardsAnalysis>;

export function GetPerformanceMetrics(arg1:models.StatsFilter):Promise<models.PerformanceMetrics>;

export function GetPickAlternatives(arg1:string,arg2:number,arg3:number):Promise<pickquality.PickQuality>;

export function GetQuestHistory(arg1:string,arg2:string,arg3:number):Promise<Array<models.Quest>>;

export function GetQuestStats(arg1:string,arg2:string):Promise<models.QuestStats>;

export function GetRankProgression(arg1:string):Promise<models.RankProgression>;

export function GetRankProgressionTimeline(arg1:string,arg2:time.Time,arg3:time.Time,arg4:storage.TimelinePeriod):Promise<storage.RankTimeline>;

export function GetReplayStatus():Promise<main.ReplayStatus>;

export function GetSetCards(arg1:string):Promise<Array<models.SetCard>>;

export function GetStats(arg1:models.StatsFilter):Promise<models.Statistics>;

export function GetStatsByDeck(arg1:models.StatsFilter):Promise<Record<string, models.Statistics>>;

export function GetStatsByFormat(arg1:models.StatsFilter):Promise<Record<string, models.Statistics>>;

export function GetTrendAnalysis(arg1:time.Time,arg2:time.Time,arg3:string,arg4:Array<string>):Promise<storage.TrendAnalysis>;

export function ImportFromFile():Promise<void>;

export function ImportLogFile():Promise<main.ImportLogFileResult>;

export function Initialize(arg1:string):Promise<void>;

export function PauseReplay():Promise<void>;

export function PredictDraftWinRate(arg1:string):Promise<prediction.DeckPrediction>;

export function RecalculateAllDraftGrades():Promise<number>;

export function ReconnectToDaemon():Promise<void>;

export function RefreshSetCards(arg1:string):Promise<number>;

export function RefreshSetRatings(arg1:string,arg2:string):Promise<void>;

export function RepairDraftSession(arg1:string):Promise<void>;

export function ResumeReplay():Promise<void>;

export function SetDaemonPort(arg1:number):Promise<void>;

export function StartPoller():Promise<void>;

export function StartReplayWithFileDialog(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function StopPoller():Promise<void>;

export function StopReplay():Promise<void>;

export function SwitchToDaemonMode():Promise<void>;

export function SwitchToStandaloneMode():Promise<void>;

export function TriggerReplayLogs(arg1:boolean):Promise<void>;
